In [49]:
! pip install numpy



[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [50]:
import numpy as np


In [51]:

print(np.__version__)

2.5.1


In [52]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [53]:
# type casting into array

arr_list1=np.array(list1)
print(arr_list1)

[1 2 3]


In [54]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [55]:
# creating 2D array

list1=[1,2,3]
list2=[4,5,6]
arr_list_1_2=np.array([list1,list2])
print(arr_list_1_2)


[[1 2 3]
 [4 5 6]]


In [56]:
# creating 3D array
list1=[1,2,3]
list2=[4,5,6]
list3=[6,7,8]
arr_list_1_2_3=np.array([[list1,list2,list3]])
print(arr_list_1_2_3)

[[[1 2 3]
  [4 5 6]
  [6 7 8]]]


In [57]:
# checking dimension of array
print(arr_list_1_2.ndim)

2


In [58]:
print(arr_list_1_2_3.ndim)

3


In [59]:
# numpy array attributes

In [60]:
list1=[1,2,3.1]
list2=[4,5,6]
arr_list_1_2=np.array([list1,list2])
print(arr_list_1_2)



[[1.  2.  3.1]
 [4.  5.  6. ]]


In [61]:
print(arr_list_1_2.shape)

(2, 3)


In [62]:
print(arr_list_1_2.size)

6


In [63]:
print(arr_list_1_2.dtype)

float64


In [64]:
# array initialization method

In [65]:
# zero array
zer_arr=np.zeros((4,3))
print(zer_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [66]:
# one array
one_arr=np.ones((2,6))
print(one_arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [67]:
# creating array of our type
full_arr=np.full((3,4),6)
print(full_arr)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [68]:
# printing identity matrix of 2*2
id_arr=np.eye(2)
print(id_arr)

[[1. 0.]
 [0. 1.]]


In [69]:
# empty array( actually it is printing random elemnts)
print(np.empty(20))

[6.95204364e-310 6.95204364e-310 1.03481143e-311 4.94065646e-324
 1.03481143e-311 1.16095442e-028 1.03481143e-311 8.54626604e-072
 0.00000000e+000 1.03481143e-311 1.03481143e-311 1.03481143e-311
 0.00000000e+000 7.74694933e-321 7.76671195e-321 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]


In [70]:
# print 2D empty array
print(np.empty((2,3)))

[[1.  2.  3.1]
 [4.  5.  6. ]]


In [71]:
# range array. 1 sy 20 aur 3 ka step size

print(np.arange(1,20,3))

[ 1  4  7 10 13 16 19]


In [72]:
# dividing array in 7 chunks, arithematic mean
print(np.linspace(1,20,7))

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [73]:
# printing random elements in float form
random_arr=np.random.rand(4,3)
print(random_arr)

[[0.24765862 0.55251824 0.29970414]
 [0.6287866  0.74133582 0.97368896]
 [0.33866974 0.71653699 0.52837673]
 [0.85425302 0.34876007 0.21638287]]


In [74]:
# printing array of random integer  type

random_arr = np.random.randint(50, 100, (4, 3))
print(random_arr)

[[60 89 81]
 [82 93 58]
 [85 62 51]
 [70 73 88]]


In [75]:
# generation random float numbers in a specific range
random_arr = np.random.uniform(50, 100, (4, 3))
print(random_arr)

[[84.87678723 92.61182144 57.14017961]
 [59.48924463 60.21863267 53.93097518]
 [94.59509083 91.84368647 64.01315179]
 [91.98168041 86.78540643 68.10773515]]


In [76]:
# 4 array indexing 

In [77]:
a=[1,2,3]

In [78]:
print(a)

[1, 2, 3]


In [79]:
print(a[0])

1


In [80]:
print(a[-1])

3


In [81]:
a=np.array([1,3,5,7,9])


In [ ]:
# slicing

In [82]:
print(a[0:3])

[1 3 5]


In [83]:
print(a[-3:])

[5 7 9]


In [ ]:
# start from 0 and step size of  3
print(a[0::3])

[1 7]


In [ ]:
# working wiht 2D array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#specific row
print(arr2[1])

[4 5 6]


In [ ]:
# specific element
print(arr2[0,0])

1


In [89]:
arr2[0,0]=9
print(arr2[0,0])

9


In [90]:
arr3=np.array(([1,3,4],[4,5,6],[7,8,9]))
print(arr3)

[[1 3 4]
 [4 5 6]
 [7 8 9]]


In [91]:
print(arr3[0])

[1 3 4]


In [ ]:
# from second till last
print(arr3[1:])

[[4 5 6]
 [7 8 9]]


In [93]:
print(arr3)

[[1 3 4]
 [4 5 6]
 [7 8 9]]


In [95]:
# before comma, rows and after comma, all columns
print(arr2[:,0])

[9 4]


In [ ]:
# reshapping array i.e changing size

In [96]:
arr2.shape

(2, 3)

In [ ]:
reshaped=arr2.reshape((6,1))# 6 rows and 1 column
print(reshaped)

[[9]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
# flatten i.e convert into 1 dimensional

In [98]:
print(reshaped.flatten())

[9 2 3 4 5 6]


In [ ]:
# stacking and splliting

In [ ]:
# vertical stacking
a=np.array([1,2,3])
b=np.array([3,4,5])
print(np.vstack((a,b)))

[[1 2 3]
 [3 4 5]]


In [ ]:
# horizontal stacking
print(np.hstack((a,b)))

[1 2 3 3 4 5]


In [ ]:
# splitng

In [101]:
c=np.array(([1,2,3],[4,5,6]))
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
# horizontal split
n=np.hsplit(c,3)
print(n)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [ ]:
# vertical split
n=np.vsplit(c,2)
print(n)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
#mathematical operations on array

In [111]:
a=np.array([1,2,3])
print(a+10)
print(a-10)
print(a*10)
print(a/10)
print(a%10)
print(np.square(a))
print(np.sqrt(a))
print(np.tan(a))


[11 12 13]
[-9 -8 -7]
[10 20 30]
[0.1 0.2 0.3]
[1 2 3]
[1 4 9]
[1.         1.41421356 1.73205081]
[ 1.55740772 -2.18503986 -0.14254654]


In [112]:
a=np.array([1,32,34])
b=np.array([1,32,34])



In [116]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))

[ 2 64 68]
[0 0 0]
[   1 1024 1156]
[1. 1. 1.]
[0 0 0]


In [ ]:
# dot product
print(np.dot(a,b))

2181


In [ ]:
# cross product
print(np.cross(a,b))

[0 0 0]


In [120]:
u=np.array(([1,2,3],[4,5,6]))
print(u)

[[1 2 3]
 [4 5 6]]


In [121]:
# transpose
print(u.T)

[[1 4]
 [2 5]
 [3 6]]


In [123]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

22.333333333333332
32.0
15.107025591499548
1
34


In [ ]:
# comparing every element both array
print(a==b)

[ True  True  True]


In [ ]:
# checking whole array
print(np.array_equal(a,b))

True


In [ ]:
# handlig with nan

In [ ]:
# inf is infinity
data1=np.array([1,2,np.nan,4,np.inf])

In [ ]:
# checking where value is nan
print(np.isnan(data1))

[False False  True False False]


In [ ]:
# changing nan values into zeros
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [ ]:
# saving in the folder
np.save('test.npy',arr2)
